# Generated by Django 5.0.3 on 2024-03-07 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inmobiliaria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arriendopropiedad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.cliente'),
        ),
        migrations.AddField(
            model_name='caracteristicasinmueble',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmueble'),
        ),
        migrations.AddField(
            model_name='arriendopropiedad',
            name='inmueble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.inmueble'),
        ),
        migrations.AddField(
            model_name='pago',
            name='arriendo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inmobiliaria.arriendopropiedad'),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inmobiliaria.tipoinmueble'),
        ),
        migrations.AlterUniqueTogether(
            name='caracteristicasinmueble',
            unique_together={('inmueble', 'caracteristica')},
        ),
    ]
